runtime: nodejs10
handlers:
- url: /.*
  script: auto
  secure: always
instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.7
  target_throughput_utilization: 0.7
  min_instances: 0
  max_idle_instances: 1
  min_idle_instances: 0
  max_pending_latency: automatic
  min_pending_latency: automatic
  max_concurrent_requests: 80